In [1]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [2]:
# 지수함수 벡터화 연산
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [3]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [4]:
# 로그함수 벡터화 연산
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

# 스칼라와 벡터/행렬의 곱셈

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 벡터화 연산
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [11]:
# 0 - 11까지 3행4열로 배열 선언
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 브로드캐스팅

In [12]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [14]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [15]:
x + y

array([1, 2, 3, 4, 5])

In [16]:
x + 1

array([1, 2, 3, 4, 5])

# 차원 축소연산

In [2]:
import numpy as np
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [7]:
# 총합 출력
np.sum(x)

10

In [5]:
# 최소값 출력
x.min()

1

In [8]:
# 최대값 출력
x.max()

4

In [9]:
# 최소값의 위치
x.argmin()

0

In [10]:
# 최대값의 위치
x.argmax()

3

In [11]:
# 평균값
x.mean()

2.5

In [12]:
a = np.zeros((100,100), dtype=np.int)
a

c:\users\chrhd\anaconda3\envs\pybook\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
np.any(a != 0)

False

In [17]:
np.all(a == 0)

True

In [21]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

In [22]:
x

array([1, 2, 3, 4])

In [23]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [25]:
# axis = 0 (열 합계), axis = 1 (행 합계)
x.sum(axis=0)

array([3, 3])

In [26]:
# axis = 0 (열 합계), axis = 1 (행 합계)
x.sum(axis=1)

array([2, 4])

In [36]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
# 전체 최대값
np.max(a)

30

In [38]:
# 각 행의 합
a.sum(axis=1)

array([ 21,  57,  93, 129, 165])

In [55]:
# 각 열의 평균
a.mean(axis=0)

array([13., 14., 15., 16., 17., 18.])

In [57]:
# 각 열의 최솟값
a.min(axis=0)

array([1, 2, 3, 4, 5, 6])

In [58]:
a.argmin()

0

In [61]:
a.argmin(axis=0)

array([0, 0, 0, 0, 0, 0], dtype=int64)

In [62]:
a.argmin(axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

In [63]:
a.argmax(axis=0)

array([4, 4, 4, 4, 4, 4], dtype=int64)

In [64]:
a.argmax(axis=1)

array([5, 5, 5, 5, 5], dtype=int64)

In [65]:
a.argmax(axis=1)

array([5, 5, 5, 5, 5], dtype=int64)

In [66]:
a.sum()

465

In [67]:
a.sum(axis=0)

array([65, 70, 75, 80, 85, 90])

In [68]:
a.sum(axis=1)

array([ 21,  57,  93, 129, 165])

In [69]:
a.mean()

15.5

In [70]:
a.mean(axis=0)

array([13., 14., 15., 16., 17., 18.])

In [71]:
a.mean(axis=1)

array([ 3.5,  9.5, 15.5, 21.5, 27.5])

In [73]:
np.median(a)

15.5

In [74]:
np.median(a[0])

3.5

TypeError: _median_dispatcher() missing 1 required positional argument: 'a'

In [76]:
np.all(a)

True

In [77]:
np.any(a == 15)

True

In [78]:
np.mean(a, axis=0)

array([13., 14., 15., 16., 17., 18.])

In [79]:
np.mean(a, axis=1)

array([ 3.5,  9.5, 15.5, 21.5, 27.5])

In [80]:
np.argmax(a, axis=0)

array([4, 4, 4, 4, 4, 4], dtype=int64)

In [81]:
np.argmax(a, axis=1)

array([5, 5, 5, 5, 5], dtype=int64)