In [1]:
import numpy as np
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [2]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1,2, 3.0])
x.dtype

dtype('float64')

In [6]:
x.dtype b

SyntaxError: invalid syntax (Temp/ipykernel_5252/2222962642.py, line 1)

In [7]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [11]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [18]:
# 문자열 덧셈
x[0] + x[1]

'12'

# Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다. 다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그값을 계산하면 무한대인 np.inf가 나온다. 0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [19]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

c:\users\chrhd\anaconda3\envs\pybook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\chrhd\anaconda3\envs\pybook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [20]:
np.log(0)

c:\users\chrhd\anaconda3\envs\pybook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [21]:
np.exp(-np.inf)

0.0

# 배열 생성
Numpy는 몇가지 단순한 배열을 생성하는 명령을 제공한다.
zeros, ones
zeros_like, ones_like
empty
arange
linspace, logspace

In [22]:
# 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros 명령을 사용한다. 인수로는 배열의 크기를 뜻하는 정수를 넣는다.
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [24]:
# 2행 3열의 '0' 배열 생성
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
c = np.zeros((5,2), dtype = "i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [28]:
# 문자열 배열도 가능하지만 모든 원소의 문자열 크기가 같아야 한다. 만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있다
d = np.zeros(5, dtype='<U4')
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [30]:
# 0이 아닌 1로 초기화된 배열 생성 시 ones 명령을 사용한다.
# (2,3,4) : 3행4열의 데이터를 2개 생성
e = np.ones((2,3,4), dtype = 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [33]:
# 만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용한다.
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
# 배열이 커지면 배열 초기화하는 데에도 시간이 오래걸린다. 그래서 특정한 값으로 초기화 하지 않는 명령도 있는데, 이것이 empty 명령이다.
g = np.empty((4,3))
g

array([[7.34065290e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 7.56587583e-307, 9.96391784e-043],
       [1.27819081e+165, 2.83082125e-056, 6.18340034e+169],
       [4.85185114e-033, 4.42436483e-062, 9.95483127e-043]])

arange 명령은 넘파이 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.

In [35]:
# arange 명령은 넘파이 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.
np.arange(10) # 0 - 9...

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(3,21,3) # 시작과 끝, 단계

array([ 3,  6,  9, 12, 15, 18])

linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간 수만큼 분할한다.

In [37]:
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [38]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [39]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
# a.reshape(2, 3, 2)과 같은 결과
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

다차원 배열을 무조건 1차원으로 만드릭 위해서는 flatten이나 ravel 메서드를 사용한다.

In [50]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [53]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [54]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [55]:
x

array([0, 1, 2, 3, 4])

In [56]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 배열연결

In [58]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
a2 = np.zeros((2,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결해서 열의 수가 넓어진 배열을 만든다
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [65]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
b2 = np.zeros((2,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
# vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위 아래로 연결하여 행의 수가 더 많은 배열을 만든다.
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
# dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 
# 가장 안쪽의 원소의 차원이 증가한다. 
# 즉 가장 내부의 숫자 원소가 배열이 된다. 
# shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것이다.이 예제의 경우에는 shape 변화가 2개의 (3 x 4) -> 1개의 (3 x 4 x 2)가 된다.
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [72]:
(np.dstack([c1, c2]).shape)

(3, 4, 2)

In [73]:
# stack 명령은 dstack의 기능을 확장한 것으로 dstack처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결한다.
# axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정한다. 
# 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성된다. 
# 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 한다.
# 다음 예에서는 axis=0 이므로 가장 바깥에 값이 2인 차원이 추가된다. 즉, shape 변화는 2개의 (3 x 4) -> 1개의 (2 x 3 x 4) 이다..
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [74]:
c.shape

(2, 3, 4)

In [75]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [76]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [77]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])